import React, { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';
import { useToast } from '../context/ToastContext';
import QRCode from 'react-qr-code';
import { 
  QrCode, 
  Download, 
  Printer, 
  RefreshCw, 
  Calendar, 
  MapPin, 
  Clock,
  ShieldCheck,
  AlertCircle
} from 'lucide-react';

export const MyQRCode = () => {
  const { user } = useAuth();
  const { showToast } = useToast();

  const [activeQRCodes, setActiveQRCodes] = useState([]);
  const [selectedIndex, setSelectedIndex] = useState(0);
  const [loading, setLoading] = useState(true);

  const fetchQRCodes = async () => {
    setLoading(true);
    try {
      const qrList = await api.qrCodes.getActive();
      setActiveQRCodes(Array.isArray(qrList) ? qrList : []);
    } catch (err) {
      showToast('Failed to fetch QR codes', 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchQRCodes();
  }, []);

  const selectedQR = activeQRCodes[selectedIndex] || null;
  const selectedExam = selectedQR?.examId || null;

  // Calculate time left until QR expiry
  const getTimeLeft = () => {
    if (!selectedQR?.expiresAt) return null;
    const diff = new Date(selectedQR.expiresAt) - new Date();
    if (diff <= 0) return '00:00';
    const hours = Math.floor(diff / 3600000);
    const mins = Math.floor((diff % 3600000) / 60000);
    const secs = Math.floor((diff % 60000) / 1000);
    if (hours > 0) return `${hours}h ${mins}m`;
    return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
  };

  const [timeLeft, setTimeLeft] = useState(getTimeLeft());

  useEffect(() => {
    if (!selectedQR) return;
    const interval = setInterval(() => {
      setTimeLeft(getTimeLeft());
    }, 1000);
    return () => clearInterval(interval);
  }, [selectedQR]);

  // Get the QR value to display — use encrypted payload or base64 image
  const qrValue = selectedQR?.encryptedPayload || selectedQR?.qrBase64 || '';

  const downloadQR = () => {
    const svgElement = document.getElementById('student-qr-svg');
    if (!svgElement) return;

    const svgString = new XMLSerializer().serializeToString(svgElement);
    const svgBlob = new Blob([svgString], { type: 'image/svg+xml;charset=utf-8' });
    const URL = window.URL || window.webkitURL || window;
    const blobURL = URL.createObjectURL(svgBlob);
    
    const image = new Image();
    image.onload = () => {
      const canvas = document.createElement('canvas');
      canvas.width = 400;
      canvas.height = 400;
      const context = canvas.getContext('2d');
      context.fillStyle = '#ffffff';
      context.fillRect(0, 0, 400, 400);
      context.drawImage(image, 25, 25, 350, 350);
      
      const pngURL = canvas.toDataURL('image/png');
      const downloadLink = document.createElement('a');
      downloadLink.href = pngURL;
      downloadLink.download = `Pass_${user?.matricNumber}_${selectedExam?.courseCode || 'exam'}.png`;
      document.body.appendChild(downloadLink);
      downloadLink.click();
      document.body.removeChild(downloadLink);
      showToast('Pass image downloaded', 'success');
    };
    image.src = blobURL;
  };

  const printQR = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Access Pass - ${user?.matricNumber}</title>
          <style>
            body { font-family: monospace; text-align: center; padding: 40px; }
            .badge { border: 4px solid #000; padding: 30px; max-width: 400px; margin: 0 auto; }
            h2 { margin: 0 0 20px; font-size: 24px; font-weight: 900; }
            p { font-weight: bold; margin: 6px 0; font-size: 14px; }
            .qr { margin: 30px 0; }
          </style>
        </head>
        <body onload="window.print(); window.close();">
          <div class="badge">
            <h2>SMART ACCESS PASS</h2>
            <div class="qr">${document.getElementById('student-qr-wrapper')?.innerHTML || ''}</div>
            <p>NAME: ${user?.lastName}, ${user?.firstName}</p>
            <p>MATRIC: ${user?.matricNumber}</p>
            <p>COURSE: ${selectedExam?.courseCode} - ${selectedExam?.title}</p>
            <p>VENUE: ${selectedExam?.venue}</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="space-y-8 select-none">
      {/* Title */}
      <div className="flex items-center justify-between gap-4 border-b-4 border-black pb-4">
        <div>
          <h1 className="text-3xl font-black uppercase text-black m-0 tracking-wide">Access QR</h1>
          <p className="text-sm font-bold text-gray-500 uppercase mt-1">Your secure exam hall entry passes generated by the institution.</p>
        </div>
      </div>

      {loading ? (
        <div className="flat-card bg-white p-12 text-center border-black">
          <div className="w-10 h-10 border-4 border-t-flatBlue border-black rounded-full animate-spin mx-auto mb-4" />
          <p className="font-extrabold text-sm uppercase text-gray-500">Loading Access Passes...</p>
        </div>
      ) : activeQRCodes.length === 0 ? (
        <div className="flat-card bg-white p-12 text-center border-black max-w-xl mx-auto mt-6">
          <AlertCircle className="w-16 h-16 mx-auto mb-4 text-flatAmber" />
          <h3 className="text-xl font-black uppercase text-black">No Active QR Codes</h3>
          <p className="text-xs font-bold text-gray-500 uppercase mt-1">
            Your institution has not generated any active exam hall passes for you yet. Please contact your exam officer.
          </p>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-5 gap-8 items-start">
          
          {/* Left 2 Cols: Selection */}
          <div className="lg:col-span-2 space-y-6">
            <div className="flat-card bg-white space-y-4">
              <h3 className="font-black text-sm uppercase border-b-2 border-black pb-2 text-black">
                1. Select Exam Pass
              </h3>
              
              <div>
                <label className="block text-xs font-black uppercase tracking-wider mb-1.5 text-black">Target Course</label>
                <select
                  className="flat-select text-xs py-2 bg-no-repeat"
                  value={selectedIndex}
                  onChange={(e) => setSelectedIndex(parseInt(e.target.value, 10))}
                >
                  {activeQRCodes.map((qr, idx) => (
                    <option key={qr._id} value={idx}>
                      {qr.examId?.courseCode || 'N/A'} - {qr.examId?.title || 'Exam'}
                    </option>
                  ))}
                </select>
              </div>

              {/* Show selected exam details */}
              {selectedExam && (
                <div className="border-2 border-black p-4 bg-gray-50 space-y-3 pt-4 text-xs font-semibold text-gray-600">
                  <div className="flex items-center gap-2">
                    <Calendar className="w-4 h-4 text-flatBlue shrink-0" />
                    <span className="uppercase font-black text-black">Date:</span>
                    <span>{selectedExam.examDate ? new Date(selectedExam.examDate).toLocaleDateString() : 'TBD'}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <Clock className="w-4 h-4 text-flatBlue shrink-0" />
                    <span className="uppercase font-black text-black">Time:</span>
                    <span>{selectedExam.startTime || 'TBD'} - {selectedExam.endTime || 'TBD'}</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <MapPin className="w-4 h-4 text-flatBlue shrink-0" />
                    <span className="uppercase font-black text-black">Venue:</span>
                    <span>{selectedExam.venue || 'TBD'}</span>
                  </div>
                </div>
              )}
            </div>

            {/* Expiry info */}
            {selectedQR && (
              <div className="flat-card bg-gray-50 border-black p-4 space-y-3">
                <h4 className="font-black text-xs uppercase text-black flex items-center gap-1.5">
                  <ShieldCheck className="w-4 h-4 text-flatEmerald shrink-0" />
                  Pass Validity
                </h4>
                <p className="text-[10px] font-bold text-gray-500 uppercase leading-snug">
                  This pass was generated by your institution. It will expire automatically after the configured validity period.
                </p>
                <div className="flex justify-between items-center bg-white border-2 border-black p-2 text-xs font-black">
                  <span>EXPIRES IN:</span>
                  <span className="text-red-500 font-mono">{timeLeft || 'Calculating...'}</span>
                </div>
                <button
                  onClick={fetchQRCodes}
                  className="w-full flat-btn bg-white hover:scale-102 py-2 text-xs font-black uppercase flex items-center justify-center gap-1 cursor-pointer"
                >
                  <RefreshCw className="w-3.5 h-3.5" />
                  Refresh QR Codes
                </button>
              </div>
            )}
          </div>

          {/* Right 3 Cols: Large QR Display */}
          <div className="lg:col-span-3 flat-card bg-white flex flex-col items-center py-8">
            <h3 className="font-black text-lg uppercase border-b-4 border-black pb-3 mb-6 text-black w-full text-center">
              Student Entrance Pass
            </h3>

            {qrValue ? (
              <div className="w-full max-w-sm flex flex-col items-center space-y-6">
                
                {/* Large QR */}
                <div id="student-qr-wrapper" className="p-6 bg-white flat-border border-black hover:scale-102 transition-transform duration-200 aspect-square flex items-center justify-center">
                  <QRCode
                    id="student-qr-svg"
                    value={qrValue}
                    size={240}
                    level="H"
                    style={{ height: "auto", maxWidth: "100%", width: "100%" }}
                  />
                </div>

                {/* Display token meta */}
                <div className="w-full border-2 border-black p-4 bg-gray-50 text-left space-y-1 text-xs">
                  <div className="flex justify-between"><span className="uppercase font-black text-black">Holder</span><span className="font-extrabold text-black uppercase">{user?.lastName}, {user?.firstName}</span></div>
                  <div className="flex justify-between"><span className="uppercase font-black text-black">Matric</span><span className="font-mono text-flatBlue font-black">{user?.matricNumber}</span></div>
                  <div className="flex justify-between"><span className="uppercase font-black text-black">Exam Target</span><span className="font-extrabold text-black uppercase">{selectedExam?.courseCode || 'N/A'}</span></div>
                  <div className="flex justify-between items-center border-t border-gray-300 pt-2 mt-2"><span className="uppercase font-black text-gray-500">Security Signature</span><span className="flat-badge border bg-white px-2 py-0.5 text-[9px] font-black uppercase text-flatEmerald border-flatEmerald">SECURE PASS</span></div>
                </div>

                {/* Print/Download Button row */}
                <div className="grid grid-cols-2 gap-3 w-full">
                  <button
                    onClick={downloadQR}
                    className="flat-btn bg-white hover:scale-102 py-3 text-xs font-black uppercase flex items-center justify-center gap-1.5 cursor-pointer"
                  >
                    <Download className="w-4 h-4" />
                    Download PNG
                  </button>
                  <button
                    onClick={printQR}
                    className="flat-btn bg-black text-white hover:scale-102 py-3 text-xs font-black uppercase flex items-center justify-center gap-1.5 cursor-pointer"
                  >
                    <Printer className="w-4 h-4" />
                    Print Pass
                  </button>
                </div>

              </div>
            ) : (
              <div className="text-center py-12 flex flex-col items-center">
                <QrCode className="w-16 h-16 text-gray-300 mb-4" />
                <p className="font-black text-xs uppercase text-gray-400">Select an exam pass to view QR code</p>
              </div>
            )}
          </div>
          
        </div>
      )}
    </div>
  );
};

export default MyQRCode;
